name: ecommerce_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.3
  flutter_rating_bar: ^4.0.1
  skeletons: ^0.0.3
  provider: ^6.0.3
  firebase_core: ^1.20.1
  firebase_auth: ^3.6.3
  cloud_firestore: ^3.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Metro
      fonts:
      - asset: assets/fonts/metropolis.regular.otf
      - asset: assets/fonts/metropolis.light.otf
        weight: 200
      - asset: assets/fonts/metropolis.medium.otf
        weight: 400
      - asset: assets/fonts/metropolis.semi-bold.otf
        weight: 500
      - asset: assets/fonts/metropolis.bold.otf
        weight: 600
      - asset: assets/fonts/metropolis.black.otf
        weight: 700


